### ISSUE TITLE
style issue

### ISSUE THREAD

**Issue by abhiFSD** [Yagasaki7K/website-yagasaki#7]
<img width="1439" alt="Screenshot 2023-01-03 at 10 33 43 PM" src="https://user-images.githubusercontent.com/7696336/210405313-5d38413d-3b62-489c-87c4-e4694acab94d.png">

**Comment by Yagasaki7K** [comment]
What's the resolution did you use?

**Comment by abhiFSD** [comment]
MacBook Air M1 - chrome

**Comment by Yagasaki7K** [comment]
2560x1600?

**Comment by abhiFSD** [comment]
sorry, on chrome its look fine, but on safari when you drag side wise its responding the the touch and come all the way to the middle.

**Comment by abhiFSD** [comment]
https://user-images.githubusercontent.com/7696336/210714737-848bd071-397a-4547-a4f6-7cad6e78d974.mov

**Comment by Yagasaki7K** [comment]
I'll check it. Thank you!

**Comment by Yagasaki7K** [comment]
I built a new homepage. If you want to use the code, you can find it in the buildStorage folder.
Responsiveness still broke and I preferred to build another one than fix it. 
That CSS was very badly done, I confess, it was done by me and in a hurry.

https://github.com/Yagasaki7K/website-yagasaki/commit/0d97f2c166af03388a74fa107320c9971f3372fb
